### ISSUE TITLE
Example of multiple html pages

### ISSUE THREAD

**Issue by itsursujit** [web2033/vite-vue3-tailwind-starter#11]
Hey,

Your starter template is very helpful.
Is it possible for you to add support of multiple html pages?

For e.g.
landing.html would contain only related JS/CSS + Assets for landing pages and don't have any relation with other html
index.html would contain only related JS/CSS + Assets for authenticated pages and don't have any relation with other html

Also for landing.html I could want to mount under #landing and #app for index.html

**Comment by web2033** [comment]
Hi. If they have nothing in common, why don't you just create two separate apps?
I would use a subdomain for a landing page.
