### ISSUE TITLE
Hot reload doesn't work in components?

### ISSUE THREAD

**Issue by shadbags** [web2033/vite-vue3-tailwind-starter#157]
As title.

I am using Home.vue as follows:

```
<template>
  <div class="bg-gray-200 prose w-full">
    <h1>To-Do List from Mozilla</h1>
    <ul class="p-4">
      <li v-for="item in ToDoItems" :key="item.id">
        <to-do-item 
        :label="item.label" 
        :done="item.done" 
        :id="item.id"
        class="p-2  bg-white rounded shadow"></to-do-item>
      
      </li>
    </ul>
  </div>
</template>
```

And the component is 

```
<template>
  <div>
    <input 
    type="checkbox" 
    :id="id" 
    :checked="isDone" 
    class="form-checkbox"/>
    <label 
    :for="id"
    class="ml-4">
    {{ label }} 
    </label>
  </div>
</template>  
```

Any changes to the classes in Home come through hot reload, any changes to  the component do not.

I get the hrm update /src/tailwind.css on either save, but the browser only refreshes with the view. IE: changes to home.vue show both tailwind.css and the home.vue got reloaded, whereas changes to the component only show tailwind.css reloading.

**Comment by web2033** [comment]
Try default scaffold to compare https://vitejs.dev/guide/#scaffolding-your-first-vite-project
If I edit `src/components/ButtonRepo.vue` in this repo then it works fine with hot reload.
