### ISSUE TITLE
doesn't work with pinia

### ISSUE THREAD

**Issue by mimoo** [web2033/vite-vue3-tailwind-starter#185]
I get the following error after trying to install pinia via `npm install pinia@next`:
 
```
 > ../node_modules/vue-demi/lib/index.mjs:2:30: error: Could not resolve "@vue/composition-api/dist/vue-composition-api.esm.js" (mark it as external to exclude it from the bundle)
    2 │ ...rom '@vue/composition-api/dist/vu...
```

**Comment by dheimoz** [comment]
hey @mimoo I wonder if you could sort the issue out. If so, could you share with the community how?

Thanks!

**Comment by mimoo** [comment]
I can't remember but it was something stupid, like running npm in the wrong directory :D
