### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by naime-hossain** [web2033/vite-vue3-tailwind-starter#188]
```
 let searchList = ref([
        {
            img: '@/assets/images/products/headphone-1.jpg',
            name: 'Headphone 1',
            tech: 'Gadget',
            price: 300,
            badge: 'Sale'
        },
   
    ])

```

in the template call this :

```
   <div v-for="(item, index) in searchList" :key="index" class="flex overflow-hidden flex-row mb-6 shadow-md rounded-xl">
                    
   <div class="flex">
         <img class="w-24 object-cover" :src="item.img" alt="" />
    </div>             
  
 </div>
```

Error 
![image](https://user-images.githubusercontent.com/12586039/132184586-df18b942-1186-43c0-958c-bb33598f4f46.png)
 what am I doing wrong ? thank you

**Comment by web2033** [comment]
Try moving your `images` folder to `public`
and change `img: '@/assets/images/products/headphone-1.jpg',` to `img: '/images/products/headphone-1.jpg',`

**Comment by naime-hossain** [comment]
> Try moving your `images` folder to `public`
> and change `img: '@/assets/images/products/headphone-1.jpg',` to `img: '/images/products/headphone-1.jpg',`

I was able to fix this way, but is this the proper way ??

**Comment by web2033** [comment]
Probably a better place to ask is Discord:
Vite -> https://discord.gg/ERxKnmgfcT
Vue -> https://chat.vuejs.org
