### ISSUE TITLE
Vue Devtools not detected

### ISSUE THREAD

**Issue by rizuki96** [web2033/vite-vue3-tailwind-starter#191]
I'm trying to inspect some component, but the devtools isn't there.

**Comment by web2033** [comment]
In `dev` mode? Cos I see them
![2021-09-08_132612](https://user-images.githubusercontent.com/11320080/132493942-c6fd17a7-fdf9-4025-a85d-e59fef461dc2.png)

but not in production, which is probably an issue with the dev tools extension itself.
Not detected here too as an example https://vueuse.org/functions.html
