### ISSUE TITLE
How to set different page title?

### ISSUE THREAD

**Issue by jjaimealeman** [web2033/vite-vue3-tailwind-starter#247]
I really appreciate the hard work that went into this setup you have, so thank you very much!

I am quite new to Vue but have been using Vite + TailwindCSS in a few static projects.

---

I know the title is hard-coded `<title>Vite + Vue 3 + Tailwind CSS</title>` in `index.html`.index.html

I've read various solutions elsewhere but they all use vue-cli, or modify `src/router/index.js` which does not exist.

How do I have the default title update while navigating to another page?

For example: `<title>Vite + Vue 3 | Home</title>`
`<title>Vite + Vue 3 | About</title>`

?

**Comment by web2033** [comment]
Super dirty way to do it:
- removing the hard-coded title from index.html
- adding to `App.vue` (in template part)

```html
  <teleport to="head">
    <title>Vite + Vue 3 | {{ $route.meta.title }}</title>
  </teleport>
```

titles come from your `routes.js` file

Or consider 3-rd party addon - https://github.com/vueuse/head

**Comment by jjaimealeman** [comment]
Brilliant solution Mr. Kopich!

Super dirt is my preference as it's more "native" without relying on a 3rd party solution!

_Thanks again!_
