### ISSUE TITLE
Fantastic work!

### ISSUE THREAD

**Issue by jjaimealeman** [web2033/vite-vue3-tailwind-starter#248]
Any plans to upgrade to WindiCSS?

I would love to do this and contribute to a brilliant starter/boilerplate!

_(I've never contributed to any project before and this would be my first time!)_

**Comment by web2033** [comment]
> Any plans to upgrade to WindiCSS?

No. It doesn't make sense. Tailwind CSS is fine.

> OH, I'm always getting this error regarding the font.
> Do you get this, also?

Yes, sometimes I see it too. But it's a warning, not an error.
It enables faster font load time. You can see the difference in the `Network` tab with or without
`<link rel="preload" href="/font/Inter-roman.var.woff2" as="font" type="font/woff2" crossorigin="anonymous">`
