### ISSUE TITLE
Broken deploy

### ISSUE THREAD

**Issue by netanonima** [web2033/vite-vue3-tailwind-starter#298]
Before deploying I added set a base field on vite.config.js. 
Then I deployed using npm run build. 
I have a broken page (even without modifying any other source than that). 
Some elements are replaced by "Not Found" text.

**Comment by web2033** [comment]
Deployed where? It might need a redirect to index.html

Does build work locally?
try `npm run build` and then `npm run serve`

**Comment by netanonima** [comment]
when I do npm run build then npm run serve it works but when I upload my files on a webserver there are errors

**Comment by web2033** [comment]
Since it's a single-page app - you need to redirect all requests to `index.html`
Current example - https://github.com/web2033/vite-vue3-tailwind-starter/blob/main/netlify.toml
It depend on where you're deploying.

**Comment by netanonima** [comment]
I'm deploying it on a folder on a hestiacp on a vps (using apache). 
I don't understand how to configure to make it work. 
May I configure that toml file or vite.config.js?

**Comment by web2033** [comment]
look at this
https://gist.github.com/davemackintosh/8ac35fff747dbf2c95e1

**Comment by netanonima** [comment]
I tried all those soluctions (.htaccess document). 
It says that with vue cli I have to set a public path, I knew it because I used it on a different project but I'm using vite.... 
My errors on console are 404 errors for example for css files but the url of that files are ok.

**Comment by netanonima** [comment]
On console I only have 500 errors due to Inter-roman.var.woff2 file. 
The upper part (App.vue) I have a "Not Found" message instead of the content.

**Comment by netanonima** [comment]
For any reason the '.var' causes a type misunderstanding by mod_negotiation, if I remove it it's solved. 
Can someone explain why I'm the only one to have this problem? 
Does that '.var' have a use or can I just rename those files?
