### ISSUE TITLE
What is this route tag?

### ISSUE THREAD

**Issue by hallowcard13** [web2033/vite-vue3-tailwind-starter#306]
Can you please tell me what is this tag doing for each page? 
```

<route lang="json">
{
  "meta": {
    "title": "Home"
  }
}
</route>
```

**Comment by web2033** [comment]
It's an optional way of adding custom data to a particular route. You can remove it if you don't need it.
It comes from unplugin-vue-router: https://github.com/posva/unplugin-vue-router#sfc-route-custom-block
