### ISSUE TITLE
Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.

### ISSUE THREAD

**Issue by janhaa** [web2033/vite-vue3-tailwind-starter#71]
Hi,

for some weird reason I started to get this error:

`Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.`

although I confirmed that @vitejs/plugin-vue is installed.

Any hints?

**Comment by janhaa** [comment]
After going back to https://github.com/web2033/vite-vue3-tailwind-starter/blob/dccad5878ca1089f87547e115a937cb70267f14a/package.json and clearing package-lock and node_modules a couple times its back to working...

**Comment by web2033** [comment]
I haven't encountered that issue.
It depends on what you're importing...
If you think it's a bug, the place to report is https://github.com/vitejs/vite/issues

Be aware, that you are back to Vite v1 which is kinda abandoned...
