### ISSUE TITLE
Hot reloading ?

### ISSUE THREAD

**Issue by mkubdev** [web2033/vite-vue3-tailwind-starter#74]
Hey, nice starter. But hot-reloading feature isn't working on my side. Is everything ok ?

**Comment by web2033** [comment]
Should work. Something specific?
Try the default starter:

>npm init @vitejs/app my-vue-app --template vue

and see if it works.

**Comment by mkubdev** [comment]
Tested `npm init @vitejs/app my-vue-app --template vue` and hot-reloading isn't working. Not relative to the repos. Thanks! 

Nice starter 👍

**Comment by mkubdev** [comment]
Tested `npm init @vitejs/app my-vue-app --template vue` and hot-reloading isn't working. Not relative to the repos. Thanks!

Using node **v14.15.4** and **WSL1**

Nice starter 👍
